name: Main
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, workflow_dispatch]
jobs:
  BuilAndTest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          yarn
      - name: Run Unit test
        run: |
            yarn test
      - name: Run Integration tests
        run: |
            yarn build
            yarn test:e2e
      - name: Publish Test Report
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'reports/*.xml'
      
